name: "ART"

web: "[mootools.net](http://mootools.net)"

description: "The graphics framework."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: ["[Valerio Proietti](http://mad4milk.net)"]

sources:
  - "Source/ART.js"
  - "Source/ART.SVG.js"
  - "Source/ART.VML.js"
  - "Source/ART.Base.js"
  - "Source/ART.Path.js"
  - "Source/ART.Shapes.js"
  - "Source/ART.Font.js"
  - "Fonts/Moderna.js"
  - "Fonts/Moderna.Bold.js"

external repositories:
  color:
    git: git://github.com/kamicane/color.git
    local: Color/package.yml
  table:
    git: git://github.com/kamicane/table.git
    local: Table/package.yml
  core:
    git: git://github.com/mootools/mootools-core.git
    local: MooTools/package.yml
